---
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_DEFAULT_STYLE: prettier
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          VALIDATE_NATURAL_LANGUAGE: false
